[package]
name = "tmpl-leptos"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[dependencies]
tmpls = { version = "*", path = ".." }

leptos = { version = "0.8", features = ["ssr"] }
